### ISSUE TITLE
Status of this org and rust std on vita

### ISSUE THREAD

**Issue by nikarh** [vita-rust/psp2-sys#5]
Hi,

In the last couple of weeks, I have managed to compile rust `std` for ps vita (via vitasdk newlib).

I have made PR's to `rust-lang/libc`, `rust-lang/backtrace-rs`, `rust-random/rand`, and of course `rust-lang/rust`. Also I made some contributions to `glium` and `vitagl` in order to make them work together. As of writing this, all of my PR's but the std itself are merged, and `rust-lang/rust` PR is approved, and will probably be merged soon.

Unfortunately, I don't have the capacity to test the whole scope of std, but a couple of things I've tested:
- Allocations work (e.g. Vec)
- Concurrency primitives work (atomics, mutexes, etc.)
- Random works (e.g. HashMap)
- rust-sdl2 works
- Attempts of backtrace unwinding crash real hardware, and go into an infinite allocation loop on an emulator
- FS access should mostly work
- Networking is uncharted territory for now. I've tried building `reqwest`, but it depends on some of the tokio stuff, requiring unix sockets and `select` API, not sure if it would be possible to port that.

It would be amazing if there were other people willing to work on that/support that effort.
So, my question is, what's the status of this org? I think it would be nice to have some guides and examples for rust+std+vita stuff in this org.

**Comment by nikarh** [comment]
Vita rust std support is merged to master now, should be in tomorrows nightly :partying_face:

**Comment by althonos** [comment]
Congrats @nikarh ! I started this a long time ago and frankly I don't have access to my Vita anymore after moving places, so I'm not sure I can continue working on this as energetically. I'd be happy to add you as a co-owner if you have projects in mind :smiley:

**Comment by nikarh** [comment]
Thanks! Yeah, I would appreciate that!

I would like to do the following at least:
- Make an org-level README, like https://github.com/rust3ds
- Make a new repo with some examples with rust std and vita (with README's and cargo make makefiles for all steps from building lib to creating a vpk)
- Create an empty repo for tracking std support issues (don't want to spam rust-lang/rust)
- Rationalize the purpose of vitalibc, vita, allocator, common and deblockator repos with std support, and if there seems to be no use for them archive them. I suppose an allocator/deblockator may be useful for writing kernel modules in Rust, because for that one would probably never want to use newlib and std, but I am not sure if there would be any interest in developing kernel modules in Rust for vita

What do you think of that?

**Comment by nikarh** [comment]
Anyway, as far as I can tell there are at least some people interested in moving forward with Rust on ps vita, so I would be happy, to help move this thing forward under the umbrella of this org.

**Comment by althonos** [comment]
Hi @nikarh , all of this sounds very reasonable :) I sent you an invite, hopefully with the member status you have enough permissions to do all of the above; if not, I'll make you a co-owner.

**Comment by nikarh** [comment]
Amazing, thank you! I'll ping you then if these permissions won't be enough.

**Comment by nikarh** [comment]
@althonos I guess I will need co-owner permission though, I want to host a docker image on ghcr and can't make it public with current permissions. (This one https://github.com/orgs/vita-rust/packages/container/vitasdk-rs/settings)

**Comment by nikarh** [comment]
Also it seems that I don't have write access to existing repos, so I can't approve/merge pr's. I think co-owner permission would solve that.

**Comment by althonos** [comment]
I made you a co-owner, this should solve the problem :)
